apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskapp
  template:
    metadata:
      labels:
        app: taskapp
    spec:
      containers:
        - name: taskapp
          image: kaiburr-taskapp:v1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/tasksdb
---
apiVersion: v1
kind: Service
metadata:
  name: taskapp
spec:
  type: NodePort
  selector:
    app: taskapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
